In [168]:
import pandas as pd
import numpy as np

In [169]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [170]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [171]:
movies.shape

(4803, 20)

In [172]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [173]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [174]:
movies = movies.merge(credits , on='title')

In [175]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [176]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [177]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [178]:
movies.shape

(4809, 7)

In [179]:
movies.dropna(inplace=True)

In [180]:
import ast

In [181]:
def convert(text):
    l =[]
    for i in ast.literal_eval(text):
        l.append(i['name'])
    return l

In [182]:
movies['genres'] = movies['genres'].apply(convert)

In [183]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [184]:
movies['keywords'] = movies['keywords'].apply(convert)

In [185]:
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [186]:
def conert3(text):
    l=[]
    count = 0;
    for i in  ast.literal_eval(text):
        if(count < 3):
            l.append(i['name'])
            count += 1
    return l

In [187]:
movies['cast'] = movies['cast'].apply(conert3)

In [188]:
movies['cast'][0]

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [189]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [190]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [191]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [192]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [193]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [194]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [195]:

movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [196]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [197]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [198]:
movies['tags'] = movies['overview'] + movies['cast'] + movies['crew'] + movies['keywords'] + movies['genres']

In [199]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [200]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])

In [201]:
new

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [202]:
new['tags'] = new['tags'].apply(lambda x:" ".join(x))

In [203]:
new

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [204]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [206]:
vector = cv.fit_transform(new['tags']).toarray()

In [207]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [208]:
vector.shape

(4806, 5000)

In [209]:
from sklearn.metrics.pairwise import cosine_similarity

In [211]:
similarity = cosine_similarity(vector)

In [212]:
new[new['title'] == 'The Lego Movie'].index[0]

np.int64(744)

In [222]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

SyntaxError: invalid syntax (3300077181.py, line 3)

In [220]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Ender's Game
Aliens vs Predator: Requiem
Independence Day

In [215]:
import pickle

In [216]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [223]:
sorted(list(enumerate(similarity[5])),reverse=True,key = lambda x: x[1])

[(5, np.float64(1.0000000000000004)),
 (30, np.float64(0.4850712500726659)),
 (159, np.float64(0.44808962688896314)),
 (38, np.float64(0.3299984002886406)),
 (20, np.float64(0.2891216547914559)),
 (1536, np.float64(0.2533201985524494)),
 (1267, np.float64(0.22278319716975167)),
 (10, np.float64(0.21938172723813917)),
 (2646, np.float64(0.21110016546037452)),
 (788, np.float64(0.19681830757831292)),
 (79, np.float64(0.19446111706564928)),
 (784, np.float64(0.19446111706564925)),
 (813, np.float64(0.18999014891433705)),
 (2435, np.float64(0.18712029714127995)),
 (215, np.float64(0.18382665829627504)),
 (1297, np.float64(0.17937941173234997)),
 (182, np.float64(0.17712297710801903)),
 (583, np.float64(0.17285432628057715)),
 (870, np.float64(0.17083256870359279)),
 (14, np.float64(0.16568337391590277)),
 (26, np.float64(0.16568337391590277)),
 (3609, np.float64(0.16477051091432693)),
 (1440, np.float64(0.16169041669088866)),
 (4504, np.float64(0.1600320096032011)),
 (4280, np.float64(0.1584236068762679)),
 (115, np.float64(0.15695698526580623)),
 (2788, np.float64(0.15686274509803919)),
 (4133, np.float64(0.15655607277128736)),
 (2817, np.float64(0.1560152902477031)),
 (3156, np.float64(0.15534712747612348)),
 (4502, np.float64(0.15534712747612348)),
 (1036, np.float64(0.1530809058942434)),
 (1192, np.float64(0.1527830828380352)),
 (1666, np.float64(0.1527830828380352)),
 (1561, np.float64(0.151247535495505)),
 (2876, np.float64(0.14969623771302396)),
 (3871, np.float64(0.14956440480527305)),
 (431, np.float64(0.14947849761564372)),
 (9, np.float64(0.1494784976156437)),
 (105, np.float64(0.149270358506633)),
 (3131, np.float64(0.149270358506633)),
 (4268, np.float64(0.149270358506633)),
 (198, np.float64(0.14852213144650112)),
 (232, np.float64(0.14852213144650112)),
 (4636, np.float64(0.14852213144650112)),
 (4597, np.float64(0.14777011582226215)),
 (196, np.float64(0.14625448482542613)),
 (7, np.float64(0.14611900125320157)),
 (1137, np.float64(0.14462030521243743)),
 (539, np.float64(0.14408763192842222)),
 (1180, np.float64(0.14408763192842222)),
 (3226, np.float64(0.1434299943928958)),
 (1453, np.float64(0.1429762897859917)),
 (545, np.float64(0.14201432049934523)),
 (41, np.float64(0.14147911460452758)),
 (2886, np.float64(0.14147911460452758)),
 (1156, np.float64(0.14002800840280097)),
 (3376, np.float64(0.14002800840280097)),
 (4008, np.float64(0.14002800840280097)),
 (1305, np.float64(0.1386206560167344)),
 (413, np.float64(0.13812277665483924)),
 (1361, np.float64(0.13730875909527243)),
 (1654, np.float64(0.13730875909527243)),
 (2223, np.float64(0.13730875909527243)),
 (4667, np.float64(0.13730875909527243)),
 (3172, np.float64(0.1372549019607843)),
 (1133, np.float64(0.13685715184712186)),
 (1671, np.float64(0.1366935298661441)),
 (210, np.float64(0.13629325512727639)),
 (2148, np.float64(0.13629325512727639)),
 (910, np.float64(0.13592873654160803)),
 (1202, np.float64(0.1345345587992625)),
 (809, np.float64(0.13338778844417354)),
 (1214, np.float64(0.1328422328310143)),
 (511, np.float64(0.13231403100624076)),
 (931, np.float64(0.13231403100624076)),
 (2390, np.float64(0.13201967239688991)),
 (129, np.float64(0.13121220505220862)),
 (242, np.float64(0.13001274187308592)),
 (869, np.float64(0.13001274187308592)),
 (3970, np.float64(0.1284985132406471)),
 (127, np.float64(0.12849851324064707)),
 (3254, np.float64(0.1281244265276946)),
 (72, np.float64(0.1278274981412284)),
 (1360, np.float64(0.1278274981412284)),
 (3363, np.float64(0.12782749814122837)),
 (3364, np.float64(0.12782749814122837)),
 (3924, np.float64(0.12782749814122837)),
 (15, np.float64(0.1266600992762247)),
 (3023, np.float64(0.1266600992762247)),
 (4308, np.float64(0.1266600992762247)),
 (1869, np.float64(0.12603505443580718)),
 (2111, np.float64(0.12603505443580718)),
 (942, np.float64(0.1257488637069642)),
 (1742, np.float64(0.1257488637069642)),
 (47, np.float64(0.12550124509378383)),
 (1766, np.float64(0.12524485821702988)),
 (2630, np.float64(0.12524485821702988)),
 (2804, np.float64(0.12524485821702988)),
 (3405, np.float64(0.12524485821702988)),
 (4126, np.float64(0.12524485821702988)),
 (1, np.float64(0.12376844287208427)),
 (241, np.float64(0.12376844287208427)),
 (572, np.float64(0.12349309560582472)),
 (939, np.float64(0.1234930956058247)),
 (4399, np.float64(0.12255110553085002)),
 (4544, np.float64(0.12222646627042817)),
 (101, np.float64(0.12187873735452179)),
 (3652, np.float64(0.1212678125181665)),
 (4477, np.float64(0.1212678125181665)),
 (126, np.float64(0.12007302660701852)),
 (2179, np.float64(0.12007302660701852)),
 (2329, np.float64(0.12002400720240082)),
 (56, np.float64(0.1194162868053064)),
 (3797, np.float64(0.1194162868053064)),
 (169, np.float64(0.11881770515720091)),
 (1099, np.float64(0.11881770515720091)),
 (0, np.float64(0.1183452670827877)),
 (339, np.float64(0.1183452670827877)),
 (4224, np.float64(0.1176470588235294)),
 (537, np.float64(0.11679143249475675)),
 (715, np.float64(0.11679143249475675)),
 (1124, np.float64(0.11679143249475675)),
 (1278, np.float64(0.11679143249475675)),
 (1601, np.float64(0.11679143249475675)),
 (3619, np.float64(0.11679143249475675)),
 (3674, np.float64(0.11679143249475675)),
 (4357, np.float64(0.11679143249475675)),
 (40, np.float64(0.11669000700233413)),
 (187, np.float64(0.11669000700233413)),
 (370, np.float64(0.11669000700233413)),
 (2476, np.float64(0.1165103456070926)),
 (2997, np.float64(0.1165103456070926)),
 (143, np.float64(0.11540595721692304)),
 (2679, np.float64(0.1151023138790327)),
 (174, np.float64(0.11510231387903269)),
 (322, np.float64(0.11510231387903269)),
 (903, np.float64(0.1143323900950059)),
 (1090, np.float64(0.1143323900950059)),
 (2492, np.float64(0.1143323900950059)),
 (2946, np.float64(0.1143323900950059)),
 (3314, np.float64(0.1143323900950059)),
 (3944, np.float64(0.1143323900950059)),
 (4214, np.float64(0.1143323900950059)),
 (1271, np.float64(0.11357771260606365)),
 (3633, np.float64(0.11328823680740416)),
 (124, np.float64(0.11328823680740414)),
 (160, np.float64(0.1124361990855662)),
 (48, np.float64(0.11227217828476796)),
 (3128, np.float64(0.11227217828476796)),
 (3378, np.float64(0.11211213233271873)),
 (4228, np.float64(0.11211213233271873)),
 (134, np.float64(0.11202240672224079)),
 (691, np.float64(0.11202240672224079)),
 (1075, np.float64(0.11202240672224079)),
 (1199, np.float64(0.11202240672224079)),
 (1799, np.float64(0.11202240672224079)),
 (3801, np.float64(0.11202240672224079)),
 (4704, np.float64(0.11202240672224079)),
 (4122, np.float64(0.11070186069251191)),
 (103, np.float64(0.1103194697029383)),
 (68, np.float64(0.10984700727621795)),
 (94, np.float64(0.10984700727621795)),
 (1094, np.float64(0.10984700727621795)),
 (1470, np.float64(0.10984700727621795)),
 (2116, np.float64(0.10984700727621795)),
 (2392, np.float64(0.10984700727621795)),
 (403, np.float64(0.1093805635246459)),
 (4046, np.float64(0.10938056352464588)),
 (271, np.float64(0.10934350421017384)),
 (740, np.float64(0.10934350421017384)),
 (2670, np.float64(0.10846522890932807)),
 (2973, np.float64(0.10846522890932807)),
 (4794, np.float64(0.10846522890932807)),
 (543, np.float64(0.10803395392536072)),
 (1430, np.float64(0.10779361112725909)),
 (139, np.float64(0.10757249579467186)),
 (1894, np.float64(0.10757249579467186)),
 (420, np.float64(0.1067703554397455)),
 (1143, np.float64(0.1067703554397455)),
 (1200, np.float64(0.1067703554397455)),
 (1628, np.float64(0.1067703554397455)),
 (3786, np.float64(0.1067703554397455)),
 (3860, np.float64(0.1067014491044368)),
 (17, np.float64(0.10670144910443678)),
 (31, np.float64(0.10585122480499261)),
 (122, np.float64(0.10585122480499261)),
 (1304, np.float64(0.10585122480499261)),
 (2248, np.float64(0.10585122480499261)),
 (3528, np.float64(0.10585122480499261)),
 (3858, np.float64(0.10585122480499261)),
 (4644, np.float64(0.10585122480499261)),
 (212, np.float64(0.10555008273018726)),
 (2031, np.float64(0.10555008273018725)),
 (208, np.float64(0.10502100630210073)),
 (4129, np.float64(0.10502100630210073)),
 (4368, np.float64(0.10502100630210073)),
 (4325, np.float64(0.10437071518085825)),
 (21, np.float64(0.10401019349846874)),
 (1077, np.float64(0.10401019349846874)),
 (1899, np.float64(0.10401019349846874)),
 (4686, np.float64(0.10401019349846874)),
 (1827, np.float64(0.10323001737691674)),
 (1906, np.float64(0.10323001737691674)),
 (1993, np.float64(0.10323001737691674)),
 (1998, np.float64(0.10323001737691674)),
 (4512, np.float64(0.10323001737691674)),
 (3404, np.float64(0.1026428638853414)),
 (349, np.float64(0.10226199851298272)),
 (356, np.float64(0.10226199851298272)),
 (1002, np.float64(0.10226199851298272)),
 (4752, np.float64(0.10226199851298272)),
 (402, np.float64(0.1022619985129827)),
 (1132, np.float64(0.1022619985129827)),
 (1418, np.float64(0.1022619985129827)),
 (83, np.float64(0.10212592127570835)),
 (618, np.float64(0.10212592127570835)),
 (44, np.float64(0.10188534162169866)),
 (189, np.float64(0.10188534162169866)),
 (205, np.float64(0.10188534162169866)),
 (1181, np.float64(0.10188534162169866)),
 (1474, np.float64(0.10188534162169866)),
 (2271, np.float64(0.10188534162169866)),
 (2293, np.float64(0.10188534162169866)),
 (3511, np.float64(0.10188534162169866)),
 (1216, np.float64(0.10105651043180541)),
 (3069, np.float64(0.10059909096557137)),
 (315, np.float64(0.10059909096557136)),
 (2118, np.float64(0.10059909096557136)),
 (3443, np.float64(0.10059909096557136)),
 (69, np.float64(0.1005659937148103)),
 (610, np.float64(0.10041928905068676)),
 (1860, np.float64(0.10002000600200069)),
 (435, np.float64(0.09901475429766743)),
 (1498, np.float64(0.09901475429766743)),
 (1517, np.float64(0.09901475429766743)),
 (1936, np.float64(0.09901475429766743)),
 (2255, np.float64(0.09901475429766743)),
 (2780, np.float64(0.09901475429766743)),
 (2911, np.float64(0.09901475429766743)),
 (3719, np.float64(0.09901475429766743)),
 (3830, np.float64(0.09901475429766743)),
 (805, np.float64(0.09901475429766741)),
 (859, np.float64(0.09901475429766741)),
 (1140, np.float64(0.09901475429766741)),
 (1235, np.float64(0.09901475429766741)),
 (1855, np.float64(0.09901475429766741)),
 (2383, np.float64(0.09901475429766741)),
 (2982, np.float64(0.09901475429766741)),
 (3089, np.float64(0.09901475429766741)),
 (3093, np.float64(0.09901475429766741)),
 (1320, np.float64(0.0980392156862745)),
 (46, np.float64(0.09750298988361743)),
 (203, np.float64(0.09750298988361743)),
 (1823, np.float64(0.09750298988361743)),
 (4675, np.float64(0.09750298988361743)),
 (2020, np.float64(0.09750298988361741)),
 (3003, np.float64(0.09750298988361741)),
 (1392, np.float64(0.09709195467257717)),
 (2209, np.float64(0.09709195467257717)),
 (81, np.float64(0.09701425001453318)),
 (627, np.float64(0.09637388493048532)),
 (1723, np.float64(0.09637388493048532)),
 (2208, np.float64(0.09637388493048532)),
 (4016, np.float64(0.09637388493048532)),
 (2594, np.float64(0.09617163101410253)),
 (746, np.float64(0.09605842128561481)),
 (1032, np.float64(0.09605842128561481)),
 (2682, np.float64(0.09605842128561481)),
 (3541, np.float64(0.09605842128561481)),
 (777, np.float64(0.09527699174583823)),
 (4131, np.float64(0.09527699174583823)),
 (460, np.float64(0.09467621366623016)),
 (890, np.float64(0.09467621366623016)),
 (1784, np.float64(0.09467621366623016)),
 (116, np.float64(0.09467621366623015)),
 (1384, np.float64(0.09467621366623015)),
 (3496, np.float64(0.09467621366623015)),
 (2418, np.float64(0.09440686400617013)),
 (570, np.float64(0.09393364366277242)),
 (1172, np.float64(0.09393364366277242)),
 (1290, np.float64(0.09393364366277242)),
 (4403, np.float64(0.09393364366277242)),
 (3397, np.float64(0.09356014857063998)),
 (507, np.float64(0.09356014857063996)),
 (1853, np.float64(0.09356014857063996)),
 (37, np.float64(0.09335200560186731)),
 (131, np.float64(0.09335200560186731)),
 (985, np.float64(0.09335200560186731)),
 (1610, np.float64(0.09335200560186731)),
 (3282, np.float64(0.09335200560186731)),
 (3345, np.float64(0.09335200560186731)),
 (3745, np.float64(0.09335200560186731)),
 (3750, np.float64(0.09335200560186731)),
 (1280, np.float64(0.09273581401244287)),
 (2102, np.float64(0.09273581401244287)),
 (1957, np.float64(0.09208185110322616)),
 (2177, np.float64(0.09208185110322616)),
 (3572, np.float64(0.09208185110322616)),
 (1483, np.float64(0.09193289141911525)),
 (100, np.float64(0.09166984970282113)),
 (325, np.float64(0.09166984970282113)),
 (422, np.float64(0.09166984970282113)),
 (505, np.float64(0.09166984970282113)),
 (562, np.float64(0.09166984970282113)),
 (773, np.float64(0.09166984970282113)),
 (1319, np.float64(0.09166984970282113)),
 (1516, np.float64(0.09166984970282113)),
 (1733, np.float64(0.09166984970282113)),
 (2923, np.float64(0.09166984970282113)),
 (3053, np.float64(0.09166984970282113)),
 (3779, np.float64(0.09166984970282113)),
 (4190, np.float64(0.09166984970282113)),
 (4521, np.float64(0.09166984970282113)),
 (16, np.float64(0.09086217008485092)),
 (36, np.float64(0.09086217008485092)),
 (535, np.float64(0.09086217008485092)),
 (563, np.float64(0.09086217008485092)),
 (1248, np.float64(0.09086217008485092)),
 (3100, np.float64(0.09086217008485092)),
 (3150, np.float64(0.09086217008485092)),
 (727, np.float64(0.09059765083337043)),
 (2077, np.float64(0.09038769075777339)),
 (2005, np.float64(0.08968970586617499)),
 (2025, np.float64(0.08968970586617499)),
 (2523, np.float64(0.08968970586617499)),
 (3029, np.float64(0.08968970586617499)),
 (3065, np.float64(0.08968970586617499)),
 (3321, np.float64(0.08968970586617499)),
 (3700, np.float64(0.08968970586617499)),
 (3702, np.float64(0.08968970586617499)),
 (1309, np.float64(0.08964374649555988)),
 (2969, np.float64(0.08964374649555988)),
 (61, np.float64(0.0895622151039798)),
 (233, np.float64(0.0895622151039798)),
 (1289, np.float64(0.0895622151039798)),
 (1565, np.float64(0.0895622151039798)),
 (1662, np.float64(0.0895622151039798)),
 (2402, np.float64(0.0895622151039798)),
 (2580, np.float64(0.0895622151039798)),
 (2757, np.float64(0.0895622151039798)),
 (3211, np.float64(0.0895622151039798)),
 (4779, np.float64(0.0895622151039798)),
 (78, np.float64(0.08856148855400953)),
 (168, np.float64(0.08856148855400953)),
 (605, np.float64(0.08856148855400953)),
 (3078, np.float64(0.08856148855400953)),
 (3593, np.float64(0.08856148855400953)),
 (3715, np.float64(0.08856148855400953)),
 (4453, np.float64(0.08856148855400953)),
 (4621, np.float64(0.08856148855400953)),
 (238, np.float64(0.0882093540041605)),
 (85, np.float64(0.08807354275501537)),
 (33, np.float64(0.08759357437106756)),
 (263, np.float64(0.08759357437106756)),
 (466, np.float64(0.08759357437106756)),
 (935, np.float64(0.08759357437106756)),
 (1145, np.float64(0.08759357437106756)),
 (1240, np.float64(0.08759357437106756)),
 (1327, np.float64(0.08759357437106756)),
 (1345, np.float64(0.08759357437106756)),
 (1497, np.float64(0.08759357437106756)),
 (1895, np.float64(0.08759357437106756)),
 (3168, np.float64(0.08759357437106756)),
 (224, np.float64(0.0875175052517506)),
 (1701, np.float64(0.08747480336813908)),
 (4266, np.float64(0.08747480336813908)),
 (4319, np.float64(0.08712136837380641)),
 (184, np.float64(0.08642716314028857)),
 (407, np.float64(0.08642716314028857)),
 (591, np.float64(0.08642716314028857)),
 (1069, np.float64(0.08642716314028857)),
 (1116, np.float64(0.08642716314028857)),
 (1231, np.float64(0.08642716314028857)),
 (1385, np.float64(0.08642716314028857)),
 (1710, np.float64(0.08642716314028857)),
 (2350, np.float64(0.08642716314028857)),
 (2607, np.float64(0.08642716314028857)),
 (84, np.float64(0.08618128166583651)),
 (299, np.float64(0.08618128166583651)),
 (1731, np.float64(0.08618128166583651)),
 (202, np.float64(0.08574929257125442)),
 (359, np.float64(0.08574929257125442)),
 (695, np.float64(0.08574929257125442)),
 (781, np.float64(0.08574929257125442)),
 (1348, np.float64(0.08574929257125442)),
 (1829, np.float64(0.08574929257125442)),
 (2097, np.float64(0.08574929257125442)),
 (2657, np.float64(0.08574929257125442)),
 (4735, np.float64(0.08553571990445116)),
 (2211, np.float64(0.0854162843517964)),
 (2449, np.float64(0.0854162843517964)),
 (3815, np.float64(0.0854162843517964)),
 (3842, np.float64(0.0854162843517964)),
 (509, np.float64(0.08541628435179639)),
 (674, np.float64(0.08541628435179639)),
 (3159, np.float64(0.08541628435179639)),
 (419, np.float64(0.0844400661841498)),
 (933, np.float64(0.0844400661841498)),
 (1274, np.float64(0.0844400661841498)),
 (1782, np.float64(0.0844400661841498)),
 (3990, np.float64(0.0844400661841498)),
 (4065, np.float64(0.0844400661841498)),
 (1141, np.float64(0.08428695623736226)),
 (290, np.float64(0.08401680504168059)),
 (292, np.float64(0.08401680504168059)),
 (744, np.float64(0.08401680504168059)),
 (1575, np.float64(0.08401680504168059)),
 (1627, np.float64(0.08401680504168059)),
 (2367, np.float64(0.08401680504168059)),
 (2955, np.float64(0.08401680504168059)),
 (3091, np.float64(0.08401680504168059)),
 (3146, np.float64(0.08401680504168059)),
 (2556, np.float64(0.0834965721446866)),
 (2748, np.float64(0.0834965721446866)),
 (3046, np.float64(0.0834965721446866)),
 (3820, np.float64(0.0834965721446866)),
 (74, np.float64(0.08349657214468659)),
 (296, np.float64(0.08309133600292948)),
 (355, np.float64(0.08309133600292948)),
 (2052, np.float64(0.0825840139015334)),
 (165, np.float64(0.08258401390153339)),
 (262, np.float64(0.08258401390153339)),
 (629, np.float64(0.08258401390153339)),
 (868, np.float64(0.08258401390153339)),
 (1697, np.float64(0.08258401390153339)),
 (1934, np.float64(0.08258401390153339)),
 (2205, np.float64(0.08258401390153339)),
 (4178, np.float64(0.08258401390153339)),
 (478, np.float64(0.0825122952480562)),
 (736, np.float64(0.08238525545716346)),
 (2154, np.float64(0.08238525545716346)),
 (2502, np.float64(0.08238525545716346)),
 (3817, np.float64(0.08238525545716346)),
 (3985, np.float64(0.08238525545716346)),
 (4139, np.float64(0.08238525545716346)),
 (4301, np.float64(0.08238525545716346)),
 (4491, np.float64(0.08238525545716346)),
 (53, np.float64(0.08170073702056668)),
 (1100, np.float64(0.08170073702056668)),
 (1759, np.float64(0.08170073702056668)),
 (1810, np.float64(0.08170073702056668)),
 (2067, np.float64(0.08170073702056668)),
 (4343, np.float64(0.08170073702056668)),
 (119, np.float64(0.08084520834544433)),
 (442, np.float64(0.08084520834544433)),
 (593, np.float64(0.08084520834544433)),
 (2784, np.float64(0.08084520834544433)),
 (2928, np.float64(0.08084520834544433)),
 (3178, np.float64(0.08084520834544433)),
 (3273, np.float64(0.08084520834544433)),
 (3474, np.float64(0.08084520834544433)),
 (3883, np.float64(0.08084520834544433)),
 (4375, np.float64(0.08084520834544433)),
 (4405, np.float64(0.08084520834544433)),
 (4572, np.float64(0.08084520834544433)),
 (23, np.float64(0.08084520834544431)),
 (135, np.float64(0.08084520834544431)),
 (195, np.float64(0.08084520834544431)),
 (581, np.float64(0.08084520834544431)),
 (662, np.float64(0.08084520834544431)),
 (664, np.float64(0.08084520834544431)),
 (1273, np.float64(0.08084520834544431)),
 (2457, np.float64(0.08084520834544431)),
 (2782, np.float64(0.08084520834544431)),
 (4017, np.float64(0.08084520834544431)),
 (4459, np.float64(0.08084520834544431)),
 (206, np.float64(0.08031157077540443)),
 (2203, np.float64(0.08031157077540443)),
 (108, np.float64(0.08001600480160055)),
 (2107, np.float64(0.08001600480160055)),
 (3042, np.float64(0.08001600480160055)),
 (3342, np.float64(0.08001600480160055)),
 (4678, np.float64(0.07978836279039112)),
 (12, np.float64(0.07938841860374446)),
 (91, np.float64(0.07938841860374446)),
 (152, np.float64(0.07938841860374446)),
 (259, np.float64(0.07938841860374446)),
 (1427, np.float64(0.07938841860374446)),
 (1464, np.float64(0.07938841860374446)),
 (1866, np.float64(0.07938841860374446)),
 (1901, np.float64(0.07938841860374446)),
 (2231, np.float64(0.07938841860374446)),